In [1]:
import pandas as pd

#importing train dataset
train = pd.read_csv('new_college.csv')

In [2]:
print train

      Unnamed: 0  CONTROL  ADM_RATE  SATVR25  SATVR75  SATMT25  SATMT75  \
0              0        1    0.8989      370      450      350      450
1              1        1    0.8673      520      640      520      650
2              2        2       NaN      NaN      NaN      NaN      NaN
3              3        1    0.8062      510      640      510      650
4              4        1    0.5125      380      480      370      480
5              5        1    0.5655      490      620      500      640
6              6        1       NaN      NaN      NaN      NaN      NaN
7              7        1       NaN      NaN      NaN      NaN      NaN
8              8        1    0.8371      NaN      NaN      NaN      NaN
9              9        1    0.8274      520      620      540      650
10            10        2    0.6422      520      630      520      640
11            11        1       NaN      NaN      NaN      NaN      NaN
12            12        2       NaN      NaN      NaN      NaN      NaN
13            13        3    0.4366      NaN      NaN      NaN      NaN
14            14        1       NaN      NaN      NaN      NaN      NaN
15            15        1       NaN      NaN      NaN      NaN      NaN
16            16        2       NaN      NaN      NaN      NaN      NaN
17            17        1       NaN      NaN      NaN      NaN      NaN
18            18        3       NaN      NaN      NaN      NaN      NaN
19            19        1       NaN      NaN      NaN      NaN      NaN
20            20        1       NaN      NaN      NaN      NaN      NaN
21            21        1       NaN      NaN      NaN      NaN      NaN
22            22        3    0.7234      NaN      NaN      NaN      NaN
23            23        2    0.6279      420      500      420      540
24            24        2       NaN      NaN      NaN      NaN      NaN
25            25        1       NaN      NaN      NaN      NaN      NaN
26            26        1    0.8326      430      540      420      540
27            27        1       NaN      NaN      NaN      NaN      NaN
28            28        1       NaN      NaN      NaN      NaN      NaN
29            29        1       NaN      NaN      NaN      NaN      NaN
...          ...      ...       ...      ...      ...      ...      ...
7774        7774        3       NaN      NaN      NaN      NaN      NaN
7775        7775        3       NaN      NaN      NaN      NaN      NaN
7776        7776        3       NaN      NaN      NaN      NaN      NaN
7777        7777        3       NaN      NaN      NaN      NaN      NaN
7778        7778        3       NaN      NaN      NaN      NaN      NaN
7779        7779        3       NaN      NaN      NaN      NaN      NaN
7780        7780        3       NaN      NaN      NaN      NaN      NaN
7781        7781        3       NaN      NaN      NaN      NaN      NaN
7782        7782        1       NaN      NaN      NaN      NaN      NaN
7783        7783        1       NaN      NaN      NaN      NaN      NaN
7784        7784        1       NaN      NaN      NaN      NaN      NaN
7785        7785        1       NaN      NaN      NaN      NaN      NaN
7786        7786        2       NaN      NaN      NaN      NaN      NaN
7787        7787        3       NaN      NaN      NaN      NaN      NaN
7788        7788        3       NaN      NaN      NaN      NaN      NaN
7789        7789        3       NaN      NaN      NaN      NaN      NaN
7790        7790        3       NaN      NaN      NaN      NaN      NaN
7791        7791        3       NaN      NaN      NaN      NaN      NaN
7792        7792        3       NaN      NaN      NaN      NaN      NaN
7793        7793        3       NaN      NaN      NaN      NaN      NaN
7794        7794        3       NaN      NaN      NaN      NaN      NaN
7795        7795        3       NaN      NaN      NaN      NaN      NaN
7796        7796        3       NaN      NaN      NaN      NaN      NaN
7797        7797        1       NaN      NaN      NaN      NaN      NaN
7798        7798        1       NaN      NaN      NaN      NaN      NaN
7799        7799        1       NaN      NaN      NaN      NaN      NaN
7800        7800        1       NaN      NaN      NaN      NaN      NaN
7801        7801        1       NaN      NaN      NaN      NaN      NaN
7802        7802        1       NaN      NaN      NaN      NaN      NaN
7803        7803        1       NaN      NaN      NaN      NaN      NaN

      SATWR25  SATWR75  NPT4_PUB   ...     UGDS_UNKN  UGDS_WHITENH  UGDS_API  \
0         NaN      NaN     13415   ...        0.0084           NaN       NaN
1         NaN      NaN     14805   ...        0.0130           NaN       NaN
2         NaN      NaN       NaN   ...        0.2671           NaN       NaN
3         NaN      NaN     17520   ...        0.0338           NaN       NaN
4         NaN      NaN     11936   ...        0.0138           NaN       NaN
5         480      600     20916   ...        0.0028           NaN       NaN
6         NaN      NaN      6407   ...        0.0079           NaN       NaN
7         NaN      NaN       NaN   ...        0.0764           NaN       NaN
8         NaN      NaN     11915   ...        0.0641           NaN       NaN
9         510      620     17541   ...        0.0127           NaN       NaN
10        NaN      NaN       NaN   ...        0.0085           NaN       NaN
11        NaN      NaN      1873   ...        0.0232           NaN       NaN
12        NaN      NaN       NaN   ...        0.0000           NaN       NaN
13        NaN      NaN       NaN   ...        0.0117           NaN       NaN
14        NaN      NaN      5048   ...        0.0055           NaN       NaN
15        NaN      NaN      7404   ...        0.0017           NaN       NaN
16        NaN      NaN       NaN   ...        0.0195           NaN       NaN
17        NaN      NaN      4565   ...        0.0378           NaN       NaN
18        NaN      NaN       NaN   ...        0.0000           NaN       NaN
19        NaN      NaN      2681   ...        0.0002           NaN       NaN
20        NaN      NaN      6628   ...        0.0194           NaN       NaN
21        NaN      NaN      8712   ...        0.0006           NaN       NaN
22        NaN      NaN       NaN   ...        0.0157           NaN       NaN
23        NaN      NaN       NaN   ...        0.1564           NaN       NaN
24        NaN      NaN       NaN   ...        0.0448           NaN       NaN
25        NaN      NaN      7163   ...        0.0058           NaN       NaN
26        NaN      NaN     16078   ...        0.0246           NaN       NaN
27        NaN      NaN      3796   ...        0.0453           NaN       NaN
28        NaN      NaN      8799   ...        0.0001           NaN       NaN
29        NaN      NaN      5278   ...        0.0232           NaN       NaN
...       ...      ...       ...   ...           ...           ...       ...
7774      NaN      NaN       NaN   ...           NaN           NaN       NaN
7775      NaN      NaN       NaN   ...           NaN           NaN       NaN
7776      NaN      NaN       NaN   ...           NaN           NaN       NaN
7777      NaN      NaN       NaN   ...           NaN           NaN       NaN
7778      NaN      NaN       NaN   ...           NaN           NaN       NaN
7779      NaN      NaN       NaN   ...           NaN           NaN       NaN
7780      NaN      NaN       NaN   ...           NaN           NaN       NaN
7781      NaN      NaN       NaN   ...           NaN           NaN       NaN
7782      NaN      NaN       NaN   ...           NaN           NaN       NaN
7783      NaN      NaN       NaN   ...           NaN           NaN       NaN
7784      NaN      NaN       NaN   ...           NaN           NaN       NaN
7785      NaN      NaN       NaN   ...           NaN           NaN       NaN
7786      NaN      NaN       NaN   ...           NaN           NaN       NaN
7787      NaN      NaN       NaN   ...           NaN           NaN       NaN
7788      NaN      NaN       NaN   ...           NaN           NaN       NaN
7789      NaN      NaN       NaN   ...           NaN           NaN       NaN
7790      NaN      NaN       NaN   ...           NaN           NaN       NaN
7791      NaN      NaN       NaN   ...           NaN           NaN       NaN
7792      NaN      NaN       NaN   ...           NaN           NaN       NaN
7793      NaN      NaN       NaN   ...           NaN           NaN       NaN
7794      NaN      NaN       NaN   ...           NaN           NaN       NaN
7795      NaN      NaN       NaN   ...           NaN           NaN       NaN
7796      NaN      NaN       NaN   ...           NaN           NaN       NaN
7797      NaN      NaN       NaN   ...           NaN           NaN       NaN
7798      NaN      NaN       NaN   ...           NaN           NaN       NaN
7799      NaN      NaN       NaN   ...           NaN           NaN       NaN
7800      NaN      NaN       NaN   ...           NaN           NaN       NaN
7801      NaN      NaN       NaN   ...           NaN           NaN       NaN
7802      NaN      NaN       NaN   ...           NaN           NaN       NaN
7803      NaN      NaN       NaN   ...           NaN           NaN       NaN

      UGDS_API.1     OPEID                                             INSTNM  \
0            NaN    100200                           Alabama A & M University
1            NaN    105200                University of Alabama at Birmingham
2            NaN   2503400                                 Amridge University
3            NaN    105500                University of Alabama in Huntsville
4            NaN    100500                           Alabama State University
5            NaN    105100                          The University of Alabama
6            NaN    100700                  Central Alabama Community College
7            NaN    100800                            Athens State University
8            NaN    831000                    Auburn University at Montgomery
9            NaN    100900                                  Auburn University
10           NaN    101200                        Birmingham Southern College
11           NaN   1218200             Chattahoochee Valley Community College
12           NaN   1055400                          Concordia College Alabama
13           NaN   1303906                        South University-Montgomery
14           NaN    101500                 Enterprise State Community College
15           NaN    106000           James H Faulkner State Community College
16           NaN    100300                                Faulkner University
17           NaN    101700                    Gadsden State Community College
18           NaN   4187200               New Beginning College of Cosmetology
19           NaN    101800    George C Wallace State Community College-Dothan
20           NaN    787100  George C Wallace State Community College-Hance...
21           NaN    569900     George C Wallace State Community College-Selma
22           NaN    962107                      Herzing University-Birmingham
23           NaN    101900                                 Huntingdon College
24           NaN   2199700                      Heritage Christian University
25           NaN    526000    J F Drake State Community and Technical College
26           NaN    102000                      Jacksonville State University
27           NaN    102100                  Jefferson Davis Community College
28           NaN    102200                  Jefferson State Community College
29           NaN    101300             John C Calhoun State Community College
...          ...       ...                                                ...
7774         NaN    145992                            Strayer University-Katy
7775         NaN    145994               Strayer University-Northwest Houston
7776         NaN    145995                           Strayer University-Plano
7777         NaN  10145900                      Strayer University-Cedar Hill
7778         NaN  10145901                    Strayer University-North Dallas
7779         NaN  10145908                     Strayer University-San Antonio
7780         NaN  10145909                        Strayer University-Stafford
7781         NaN   4169701                                     Unitek College
7782         NaN   4176201     Twin Rivers Adult School - Grand Avenue Center
7783         NaN   4176202    Twin Rivers Adult School - Arnold Avenue Center
7784         NaN   4176205                    Greater Sacramento Urban League
7785         NaN   4176206                                              I-TAP
7786         NaN   4088301                                    WestMed College
7787         NaN   4184801                              Excel Learning Center
7788         NaN   4184802                              Excel Learning Center
7789         NaN   4205801          SAE Institute of Technology San Francisco
7790         NaN  10145905              Strayer University-Bloomington Campus
7791         NaN  10145903               Strayer University-Schaumburg Campus
7792         NaN  10145902            Strayer University-Downers Grove Campus
7793         NaN  10145906                   Strayer University-Aurora Campus
7794         NaN    869423                  Rasmussen College - Overland Park
7795         NaN   4220901  National Personal Training Institute of Cleveland
7796         NaN  10145911              Strayer University-St Louis-Brentwood
7797         NaN    157102            Georgia Military College-Augusta Campus
7798         NaN    157103           Georgia Military College-Fairburn Campus
7799         NaN    157107           Georgia Military College-Columbus Campus
7800         NaN    157101           Georgia Military College-Valdosta Campus
7801         NaN    157105      Georgia Military College-Warner Robins Campus
7802         NaN    157100                    Georgia Military College-Online
7803         NaN    157103            Georgia Military College-Stone Mountain

                   CITY  STABBR  \
0                Normal      AL
1            Birmingham      AL
2            Montgomery      AL
3            Huntsville      AL
4            Montgomery      AL
5            Tuscaloosa      AL
6        Alexander City      AL
7                Athens      AL
8            Montgomery      AL
9     Auburn University      AL
10           Birmingham      AL
11          Phenix City      AL
12                Selma      AL
13           Montgomery      AL
14           Enterprise      AL
15          Bay Minette      AL
16           Montgomery      AL
17              Gadsden      AL
18          Albertville      AL
19               Dothan      AL
20           Hanceville      AL
21                Selma      AL
22           Birmingham      AL
23           Montgomery      AL
24             Florence      AL
25           Huntsville      AL
26         Jacksonville      AL
27              Brewton      AL
28           Birmingham      AL
29               Tanner      AL
...                 ...     ...
7774            Houston      TX
7775            Houston      TX
7776              Plano      TX
7777         Cedar Hill      TX
7778             Dallas      TX
7779        San Antonio      TX
7780           Stafford      TX
7781            Fremont      CA
7782         Sacramento      CA
7783          McClellan      CA
7784         Sacramento      CA
7785         Sacramento      CA
7786             Merced      CA
7787            El Paso      TX
7788             Austin      TX
7789      San Francisco      CA
7790        Bloomington      MN
7791         Schaumburg      IL
7792      Downers Grove      IL
7793             Aurora      IL
7794      Overland Park      KS
7795   Richmond Heights      OH
7796          Brentwood      MO
7797           Martinez      GA
7798           Fairburn      GA
7799           Columbus      GA
7800           Valdosta      GA
7801      Warner Robins      GA
7802      Milledgeville      GA
7803     Stone Mountain      GA

                                                INSTURL  HIGHDEG
0                                         www.aamu.edu/        4
1                                           www.uab.edu        4
2                             www.amridgeuniversity.edu        4
3                                           www.uah.edu        4
4                        www.alasu.edu/email/index.aspx        4
5                                           www.ua.edu/        4
6                                          www.cacc.edu        2
7                                        www.athens.edu        3
8                                           www.aum.edu        4
9                                        www.auburn.edu        4
10                                         www.bsc.edu/        3
11                                           www.cv.edu        2
12                                        www.ccal.edu/        3
13                                  southuniversity.edu        4
14                                         www.escc.edu        2
15                                www.faulknerstate.edu        2
16                                     www.faulkner.edu        4
17                                 www.gadsdenstate.edu        2
18                               www.nbccosmetology.com        1
19                                      www.wallace.edu        2
20                                 www.wallacestate.edu        2
21                                         www.wccs.edu        2
22                           www.herzing.edu/birmingham        3
23                                   www.huntingdon.edu        3
24                                          www.hcu.edu        4
25                                   www.drakestate.edu        2
26                                         www.jsu.edu/        4
27                                         www.jdcc.edu        2
28                              www.jeffstateonline.com        2
29                                      www.calhoun.edu        2
...                                                 ...      ...
7774                  http://www.strayer.edu/texas/katy        0
7775     http://www.strayer.edu/texas/northwest-houston        0
7776                 http://www.strayer.edu/texas/plano        0
7777     http://http://www.strayer.edu/texas/cedar-hill        0
7778   http://http://www.strayer.edu/texas/north-dallas        0
7779    http://http://www.strayer.edu/texas/san-antonio        0
7780       http://http://www.strayer.edu/texas/stafford        0
7781                      http://www.unitekcollege.edu/        0
7782                                       www.tras.edu        0
7783                                http://www.tras.edu        0
7784                                http://www.tras.edu        0
7785                                      www.i-tap.com        0
7786                      http://www.westmedcollege.edu        0
7787                               http://www.excel.edu        0
7788                               http://www.excel.edu        0
7789                                     http://sae.edu        0
7790       http://www.strayer.edu/minnesota/bloomington        0
7791         http://www.strayer.edu/illinois/schaumburg        0
7792      http://www.strayer.edu/illinois/downers-grove        0
7793             http://www.strayer.edu/illinois/aurora        0
7794                               http://rasmussen.edu        0
7795                                http://nptiohio.edu        0
7796  http://www.strayer.edu/missouri/st-louis-brent...        0
7797              http://augusta.gmc.cc.ga.us/index.php        0
7798                      http://fairburn.gmc.cc.ga.us/        0
7799                      http://columbus.gmc.cc.ga.us/        0
7800                      http://valdosta.gmc.cc.ga.us/        0
7801                        http://robins.gmc.cc.ga.us/        0

In [3]:
alg_categories = ['CONTROL', 
                  'SATVR25', 'SATVR75', 'SATMT25', 'SATMT75', 'SATWR25', 'SATWR75',
                  'NPT4_PUB', 'NPT4_PRIV']

alg_race = ['UGDS','UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN',
            'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN',
            'UGDS_WHITENH', 'UGDS_API', 'UGDS_API']

alg_majors = ['PCIP01', 'PCIP03', 'PCIP04', 'PCIP05', 'PCIP09', 'PCIP10', 'PCIP11',
              'PCIP12', 'PCIP13', 'PCIP14', 'PCIP15', 
              'PCIP16', 'PCIP19', 'PCIP22', 'PCIP23', 'PCIP24', 'PCIP25', 'PCIP26', 'PCIP27',
              'PCIP29', 'PCIP30', 'PCIP31', 'PCIP38', 'PCIP39', 'PCIP40', 'PCIP41', 'PCIP42',
              'PCIP43', 'PCIP44', 'PCIP45', 'PCIP46',
              'PCIP47', 'PCIP48', 'PCIP49', 'PCIP50', 'PCIP51', 'PCIP52', 'PCIP54']

disp_categories = ['OPEID','INSTNM','CITY','STABBR', 'INSTURL', 'HIGHDEG','ADM_RATE']

In [4]:
"""inputs = [sat_reading, sat_writing, sat_math, pref_major, race_diversity, public_private, popul, pay]

sat_reading = Input SAT Reading Score (integer)
sat_writing = Input SAT Writing Score (integer)
sat_math = Input SAT Math Score (Integer)
    DONE!

pref_major = Type in string for desired major
    % Major exceeds at least 5%

pay = Input Integer for Maximum wanted to pay
    +- 5000
        

race_diversity = Input [0,1,2] For Low, Medium, High
    greatest population is
    Low one popul is over 0.6
    Middle one population is not over 0.6
    Low one population is not over 0.4

public_private = Input [0,1,2] for Both, Public, Private
    Check if NPT4_PUB is null or not
    Check if NPT4_PRIV is null or not
    
    If both null, output neither, include in list
    If one exists, it is either public or private
    
popul = Input [0,1,2] For Low, Medium, High
    UGDS
    small < 5000
    medium, 5000 < x < 15000
    big > 15000


"""

'inputs = [sat_reading, sat_writing, sat_math, pref_major, race_diversity, public_private, popul, pay]\nsat_reading = Input SAT Reading Score (integer)\nsat_writing = Input SAT Writing Score (integer)\nsat_math = Input SAT Math Score (Integer)\npref_major = Type in string for desired major\nrace_diversity = Input [0,1,2] For Low, Medium, High\npublic_private = Input [0,1] for Public, Private\npopul = Input [0,1,2] For Low, Medium, High\npay = Input [0,1,2] For Low, Medium, High\n'

In [11]:
for row in train['SATMT25']:
    print row, train.index[row]

 350.0 350
520.0 520
nan

IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 7804